### ISSUE TITLE
No sensors found after use combined automation

### ISSUE THREAD

**Issue by dvanderham** [remb0/Sunscreen#1]
After applying the new combined automation the following sensors are not found.

binary_sensor.sunscreen_valid_wind
binary_sensor.sunscreen_valid_rain
binary_sensor.sunscreen_valid_azimuth
binary_sensor.sunscreen_valid_elevation
binary_sensor.sunscreen_valid_irradiance
binary_sensor.sunscreen_valid_months_for_execution

are they missing new sensors in helpers of sunscreen script?

**Comment by remb0** [comment]
I updated the sunscreen.yaml automation and description of the helpers.

I hope everything is in sync now.  can you tell me?

**Comment by remb0** [comment]
closed
